version: '3.8'

services:
  bridge-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridge-app
    ports:
      - "8300:8300"
    volumes:
      - .:/app
      - ./Outputs:/app/Outputs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - network1

networks:
  network1:
    name: isaric_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
